### ISSUE TITLE
出場者編集でチーム削除が不可能となるエラー

### ISSUE THREAD

**Issue by amt012** [pjmtdw/kagetra#39]
大会結果におけるエラー

「団体戦の出場者編集で、誤って登録したチームの削除ができない」

〈「反映」時に表示されるエラー〉
undefined method `destroy' for []:Array

原因・対処法等あればご教示ください。

**Comment by pjmtdw** [comment]
https://github.com/pjmtdw/kagetra/pull/41
にて対処済み．
サーバに反映次第Closeする予定です．

**Comment by pjmtdw** [comment]
サーバに反映したので close します．
