### ISSUE TITLE
入賞／順位が削除できないエラー

### ISSUE THREAD

**Issue by amt012** [pjmtdw/kagetra#40]
大会結果・入賞歴におけるエラー

「大会結果から入賞／順位を削除しても、入賞歴での表示が残る」

なお、該当出場者を削除し出場者登録をし直しても入賞歴に残っています。

原因・対処法等あればご教示ください。

**Comment by pjmtdw** [comment]
https://github.com/pjmtdw/kagetra/pull/42 にて入賞の削除時に入賞歴の削除をするようにしました．
すでに入賞歴に存在してしまった情報の削除方法は別途用意します．

**Comment by pjmtdw** [comment]
https://github.com/pjmtdw/kagetra/pull/43 にて入賞歴と実際の大会結果を同期させるメソッドを追加しました．
CLIで実行する必要があるのでこちらでやっておきます．

**Comment by pjmtdw** [comment]
サーバに反映して，入賞歴と大会結果の同期も完了したので close します．
